[package]
name = "clashrup"
description = "Simple CLI to manage your clash service and configuration subscriptions."
version = "0.1.1"
edition = "2021"
readme = "README.md"
license = "MIT"
authors = ["spencerwooo <spencer.woo@outlook.com>"]
homepage = "https://github.com/spencerwooo/clashrup"
repository = "https://github.com/spencerwooo/clashrup"
keywords = ["cli", "clash", "network", "linux"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
colored = "2.0.0"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.5.10"
reqwest = { version = "0.11", features = ["blocking"] }
flate2 = "1.0"
shellexpand = "3.0.0"
